### PR TITLE
bring kiwidrive back?

### PR DESCRIPTION
**Pull request by ariovistus**

### CODE REVIEW

**Comment by bb010g** [comment]
I forgot, this is still useful because Girls Gen. We should probably get tests fixed soon.

**Comment by bb010g** [comment]
Are you waiting to merge?

**Comment by bb010g** [comment]
"Guillotate"?

**Comment by ariovistus** [comment]
sure, why not?

**Comment by bb010g** [comment]
No, what is Guillotate?

**Comment by leviatronix** [comment]
I think Guillotine is the nickname because of the way the network racks stick up in the air

**Comment by aebooth** [comment]
What still needs to be done on this?
I'd love to contribute if I can.....

**Comment by ariovistus** [comment]
No idea. I could stop by tomorrow around 4:45

**Comment by aebooth** [comment]
I need to be home around 5:00p tomorrow--maybe in the next couple of weeks?

**Comment by ariovistus** [comment]
sure.

**Comment by ariovistus** [comment]
@aebooth have you ever used atlassian confluence? Its a nifty knowledge sharing/wiki that I think would be valuable for the team to use. It also has a calendar addon and a stackexchange clone which I haven't used. It might be possible for us to request an open source license for it (otherwise it costs money).

**Comment by leviatronix** [comment]
I use Confluence at ATS and it works great.

**Comment by ariovistus** [comment]
say, do I get a tour of ATS sometime? I'd kinda like to see what you guys do

**Comment by aebooth** [comment]
Bump on that--I would love to see the place if we could arrange it so that I could tell kids more accurately what Software Development is like.
Plus, I know we need to build that relationship so we can take advantage of internship opportunities as they come available.

**Comment by aebooth** [comment]
As far as Atlassian Confluence goes, it looks like we could get it cheap for 10 users; I think educational pricing might not be a thing... :(
Would you want it on the cloud or locally hosted on district servers?

**Comment by ariovistus** [comment]
with an open source license, you get unlimited users. and its free. See https://www.atlassian.com/software/views/open-source-license-request

We meet all those criteria, we'd just have to make it publically accessible, which I want for the bling anyways. I say it should be in the cloud. that way we don't have to do updates/patches/etc.

I have successfully requested such a license for one of my other projects: https://pythond.atlassian.net/wiki/pages/viewrecentblogposts.action?key=pyd

**Comment by ariovistus** [comment]
well, we don't have a license on our code yet. I vote MIT

**Comment by aebooth** [comment]
Sweet deal with Atlassian.
What's the gist of the MIT license?

**Comment by ariovistus** [comment]
others can use your code, they don't have to redistribute changes. business friendly.

**Comment by aebooth** [comment]
I'm down with that.

We all need to talk about next year because Jim is pretty set on me being head coach next year. I'm very concerned about the time commitment that would represent during the busy Spring months. While researching solutions, I started looking at FTC (which runs September to January) as a possible substitute for FRC. They use smaller robots, but it is cheaper and they have a very similar format to FRC. Have you ever looked at FTC?

**Comment by leviatronix** [comment]
Another suggestion was made to use Oly's shop instead

**Comment by aebooth** [comment]
The thing about that is it would require more time from me because of the travel even though we'd get the benefit of leaving things out. If Mr. Brown wanted to be head coach, that would be a feasible solution.

**Comment by bb010g** [comment]
@ariovistus commented on [Mar 28, 2015, 9:47 AM PDT](https://github.com/Retro3223/2015-recycle-rush/pull/10#issuecomment-87263860 "2015-03-28T16:47:04Z - Replied by Github Comment Enhancer"):
> well, we don't have a license on our code yet. I vote MIT

If we're voting on licenses, I vote GPLv3. Keep it FLOSS.

**Comment by aebooth** [comment]
FLOSS is share-alike I'm guessing.
I don't see any major issues with either license, but for something like this, less restrictive is probably better.

**Comment by aebooth** [comment]
I was just looking more at FTC and they are moving to an Android control system starting next year.  Students and mentors will be able to use regular Android programming, MIT AppInventor, a FIRST specific app that allows basic configuration.
This makes FTC even more attractive to me because Android programming is a skill that can lead directly to a career--not to mention students can use their skills on hardware they may already have at home so all aspects of training will probably be easier.

**Comment by ariovistus** [comment]
@aebooth that sounds interesting

@bb010g robotpy is licensed MIT

**Comment by bb010g** [comment]
@ariovistus commented on [Mar 28, 2015, 1:27 PM PDT](https://github.com/Retro3223/2015-recycle-rush/pull/10#issuecomment-87296544 "2015-03-28T20:27:35Z - Replied by Github Comment Enhancer"):
> @bb010g robotpy is licensed MIT

Really? [It looks like they're licensed on 3-clause BSD.](https://github.com/robotpy/robotpy-wpilib/blob/master/wpilib/LICENSE.txt). Also, almost everything GNU is licensed with some sort of GPL. Anyhow, this should be set off into a separate issue if we want to keep discussing it here.


@aebooth commented on [Mar 28, 2015, 11:09 AM PDT](https://github.com/Retro3223/2015-recycle-rush/pull/10#issuecomment-87275182 "2015-03-28T18:09:41Z - Replied by Github Comment Enhancer"):
> I was just looking more at FTC and they are moving to an Android control system starting next year.  Students and mentors will be able to use regular Android programming, MIT AppInventor, a FIRST specific app that allows basic configuration.
> This makes FTC even more attractive to me because Android programming is a skill that can lead directly to a career--not to mention students can use their skills on hardware they may already have at home so all aspects of training will probably be easier.

Looking at FTC, it looks cool, but I don't think it has the appeal of FRC to possible members. You can take a FRC robot somewhere and drive it around; it's a good-sized piece of tech that they can inspect and ask about. We should talk about it at the next meeting.

**Comment by ariovistus** [comment]
They say you don't win chairman's award unless you do both FRC and FTC!

**Comment by leviatronix** [comment]
All these issues should be discussed at next meeting. FTC sounds
interesting but I don't think students will be willing to abandon FRC.

**Comment by aebooth** [comment]
Have we set a time for the next meeting yet?

**Comment by ariovistus** [comment]
idk. im never in the loop. what's the usual channel?

**Comment by leviatronix** [comment]
The next meeting has not been set. We usually discuss this at school or
over instant messaging.

**Comment by aebooth** [comment]
Good question. I think we generally meet on Monday or Tuesday so maybe we just email all the mentors and see who can come when. Them yhe kids can announce it on their chat client.

**Comment by leviatronix** [comment]
Adamson can't on Tuesday and the rest of the week is dedicated to SkillsUSA.

**Comment by aebooth** [comment]
I knew later in the week was out--I'll be coming with.
I wonder if people can make it on Monday?

**Comment by leviatronix** [comment]
Wednesday is the SkillsUSA meeting and we're leaving on Thursday. We could
try for Monday or do it Tuesday without Adamson.

**Comment by aebooth** [comment]
Adamson needs to be there--he still has a stake in what's happening, and I think his experience will be helpful during our discussion.
We could also meet after Spring Break--there isn't a ton of urgency behind this topic, and any time change is involved, it's better for everyone to have some time to do research and let the feelings of discomfort ebb a bit.

**Comment by leviatronix** [comment]
I agree, let's wait until after spring break.

**Comment by leviatronix** [comment]
Oooh speaking of useful career skills used in FRC... :D
http://robotpy.github.io/2015/03/29/pynetworktables2js-released/

**Comment by aebooth** [comment]
Sweet!
Now we just have to make a JS version of WPILib via Nodejs add-ons.... :)

**Comment by ariovistus** [comment]
how are you going to connect a joystick to the browser?

**Comment by ariovistus** [comment]
actually, that would make for a neat alternative to smartdashboard

**Comment by aebooth** [comment]
That was my initial vision for it.

**Comment by leviatronix** [comment]
They say in that article that they will release their smart dashboard code
soon

**Comment by bb010g** [comment]
@aebooth commented on [Mar 29, 2015, 10:40 AM PDT](https://github.com/Retro3223/2015-recycle-rush/pull/10#issuecomment-87449775 "2015-03-29T17:40:00Z - Replied by Github Comment Enhancer"):
> Now we just have to make a JS version of WPILib via Nodejs add-ons.... :)

I would approve of Io.js/Node.js WPILib addons. I'll see what I can do as time allows and make sure to put it on GitHub.

**Comment by aebooth** [comment]
Sweet!
I kind of want to dig into it myself.

**Comment by aebooth** [comment]
*myself as well

**Pull request closed without merging**
